version: '3'

services:
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - redis_data:/data

  db:
    container_name: auth_postgres
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - pg_data_auth:/var/lib/postgresql/data

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    stdin_open: true
    depends_on:
      - db

volumes:
  pg_data_auth: {}
  redis_data: {}
